.TH DWM 1 dwm\-VERSION
.SH NAME
dwm \- dynamic window manager
.SH SYNOPSIS
.B dwm
.RB [ \-v ]
.SH DESCRIPTION
This is a fork of suckless.org's dynamic window manager.
It has more features but can be difficult to set up so that's why this page exists.
.P
Before you make install, please edit the dwm-applications file which should be present in the dwm source code directory. The file contains variables that dwm will use for its keybinds. This file exists so you don't need to recompile every time you wanna change a keybind.
.P
This is the only part necessary to use dwm. If you'd like to customize colors, there are two different ways to do so. The first method is to use a .Xresources file with xrdb (Install using your package manager)
.P
Create ~/.Xresources and add these lines to the file:
.P
dwm.nmaster: 1
.P
dwm.font: Terminus:size=8
.P
dwm.col_background: #222222
.P
dwm.col_backgroundmid: #222222
.P
dwm.col_textnorm: #bbbbbb
.P
dwm.col_textsel: #eeeeee
.P
dwm.col_windowbordersel: #ff5e0e
.P
dwm.col_windowbordernorm: #5757ff
.P
dwm.col_tag1: #333333
.P
dwm.col_tag1_text: #eeeeee
.P
dwm.col_tag2: #333333
.P
dwm.col_tag2_text: #eeeeee
.P
dwm.col_tag3: #333333
.P
dwm.col_tag3_text: #eeeeee
.P
dwm.col_tag4: #333333
.P
dwm.col_tag4_text: #eeeeee
.P
dwm.col_tag5: #333333
.P
dwm.col_tag5_text: #eeeeee
.P
dwm.col_tag6: #333333
.P
dwm.col_tag6_text: #eeeeee
.P
dwm.col_tag7: #333333
.P
dwm.col_tag7_text: #eeeeee
.P
dwm.col_tag8: #333333
.P
dwm.col_tag8_text: #eeeeee
.P
dwm.col_tag9: #333333
.P
dwm.col_tag9_text: #eeeeee
.P
dwm.borderpx: 1
.P
dwm.snap: 32
.P
dwm.showbar: 1
.P
dwm.topbar: 1
.P
dwm.resizehints: 0
.P
dwm.mfact: 0.50
.P
dwm.startontag: 0
.P
Then simply add "xrdb ~/.Xresources" to ~/.xinitrc BEFORE dwm.
.P
The second method is to use Pywal. This assumes Pywal is already working and set up on your system and you already have a way to set a wallpaper. To use Pywal, add these lines to .xinitrc
.P
xrdb ~/.Xresources # Only if you're already using a .Xresources
.P
~/.config/dwm/wal.sh
.P
wal -R
.P
xrdb -merge ~/.cache/wal/colors.Xresources # Get rid of the -merge if you don't have a .Xresources
.P
As for keybinds, you can look at the source code yourself. This list may be slightly out of date but this should be a fairly accurate list of all keybinds.
.P
.B Alt+Shift+Enter
Opens a terminal.
.B Alt+Shift+Comma
Runs dmenu
.B Alt+Shift+s
Runs maim to take a screenshot and copies the output to the clipboard using xclip
.B Alt+Shift+f
Opens the defined file manager
.B Alt+Shift+w
Opens the defined web browser
.B Alt+Shift+o
Opens the dmpeg script in dmenu which can be used to record the screen.
.B Alt+Shift+p
Opens the genpkg script in dmenu which can be used to look up packages on the Gentoo wiki
.B Alt+Shift+c
Opens the copyout script in dmenu which can be used to copy the output of a command to the clipboard using xclip.
.B Alt+Shift+v
Opens the dsearch script in dmenu which can be used to search different search engines with dmenu
.B Alt+Shift+j
Opens the cfgedit script in dmenu which can be used to quickly open config files in your editor.
.B Control+Shift+m
Opens the defined email client on the system (Default is neomutt, remove $TERMINAL if it's a GUI)
.B Alt+Shift+t
Opens the defined text editor on the system (Default is vim, remove $TERMINAL if it's a GUI)
.B Alt+Shift+p
pkills the defined $BROWSER
.B Alt+Shift+m
Opens the defined music player on the system (Default is mocp, remove $TERMINAL if it's a GUI)
.B Control+Alt+m
pkills the defined music player on the system
.B Control
