#!/bin/sh
# dwmutils
# Written for speedie's dwm
# You can find it here: https://github.com/speedie-de/dwm
# Licensed under GNU GPLv3.


RUN_LAUNCHER=dmenu # Run launcher to use (dmenu, rofi, etc.)
SIGNAL_1=1         # Layout: Tiling
SIGNAL_2=2         # Layout: Floating
SIGNAL_3=3         # Layout: Monocle
SIGNAL_4=4         # Layout: Grid
SIGNAL_5=5         # Layout: Deck
SIGNAL_6=6         # Layout: Centered Master
SIGNAL_7=7         # Layout: Centered Floating Master
SIGNAL_8=8         # Layout: Fibonacci Spiral
SIGNAL_9=9         # Layout: Fibonacci Dwindle
SIGNAL_10=10       # Layout: Three Column
SIGNAL_11=11       # Layout: Bottom Stack Vertical
SIGNAL_12=12       # Layout: Bottom Stack Horizontal
SIGNAL_13=13       # Layout: Horizontal Grid
SIGNAL_14=14       # Layout: Tatami
SIGNAL_15=15       # Layout: Unused
SIGNAL_16=16       # Layout: Previous
SIGNAL_17=17       # Layout: Next

SIGNAL_18=18       # General: Reload resources (xrdb)
SIGNAL_19=19       # General: Set mfact (-0.05)
SIGNAL_20=20       # General: Set mfact (+0.05)
SIGNAL_21=21       # General: Toggle Scratchpad
SIGNAL_22=22       # General: Toggle Sticky

GENERAL() {
GENERALOPTS=$(printf "mfact +\nmfact -\nToggle Scratchpad\nToggle Sticky" | $RUN_LAUNCHER -l 20 -p 'What do you wanna do?')
case "$GENERALOPTS" in
"mfact +") xsetroot -name "fsignal:$SIGNAL_20" ;;
"mfact -") xsetroot -name "fsignal:$SIGNAL_19" ;;
"Toggle Scratchpad") xsetroot -name "fsignal:$SIGNAL_21" ;;
"Toggle Sticky") xsetroot -name "fsignal:$SIGNAL_22" ;;
esac
}

OPT() {
MENUOPTS=$(printf "Layout\nReload .Xresources\nSpawn\nGeneral\nExit" | $RUN_LAUNCHER -l 20 -p 'What do you wanna do?')
case "$MENUOPTS" in
"Layout") ${0} -layout && exit 0 ;;
"Reload .Xresources") ${0} -reloadxrdb && exit 0 ;;
"Spawn") ${0} -spawn && exit 0 ;;
"General") ${0} -general && exit 0 ;;
"Exit") exit 0 ;;
esac
}

HELP() {
printf "dwmutils allows you to control dwm using your terminal or dmenu/rofi.\n-- Arguments --\n-layout | Let the user select a dwm layout\n-reloadxrdb | Reload .Xresources\n-spawn | Spawn a command through dwm" | $RUN_LAUNCHER -p 'dwmutils help' -g 1 -l 20
}

case "$1" in
"-layout") SEL_LAYOUT=$(printf "Tiling\nFloating\nMonocle\nGrid\nDeck\nCentered Master\nCentered Floating Master\nFibonacci Spiral\nFibonacci Dwindle\nThree Column\nBottom Stack Vertical\nBottom Stack Horizontal\nHorizontal Grid\nTatami\nPrevious Layout\nNext Layout" | dmenu -l 20 -p "Pick a layout: ") ;;
"-spawn") printf "Not complete" ;;
"-reloadxrdb") xsetroot -name "fsignal:$SIGNAL_18" ;;
"-help") HELP ;;
"-h") HELP ;;
"-general") GENERAL ;;
"") OPT ;;
esac

case "$SEL_LAYOUT" in
"Exit") exit 0 ;;
"Tiling") xsetroot -name "fsignal:$SIGNAL_1" ;;
"Floating") xsetroot -name "fsignal:$SIGNAL_2" ;;
"Monocle") xsetroot -name "fsignal:$SIGNAL_3" ;;
"Grid") xsetroot -name "fsignal:$SIGNAL_4" ;;
"Deck") xsetroot -name "fsignal:$SIGNAL_5" ;;
"Centered Master") xsetroot -name "fsignal:$SIGNAL_6" ;;
"Centered Floating Master") xsetroot -name "fsignal:$SIGNAL_7" ;;
"Fibonacci Spiral") xsetroot -name "fsignal:$SIGNAL_8" ;;
"Fibonacci Dwindle") xsetroot -name "fsignal:$SIGNAL_9" ;;
"Three Column") xsetroot -name "fsignal:$SIGNAL_10" ;;
"Bottom Stack Vertical") xsetroot -name "fsignal:$SIGNAL_11" ;;
"Bottom Stack Horizontal") xsetroot -name "fsignal:$SIGNAL_12" ;;
"Horizontal Grid") xsetroot -name "fsignal:$SIGNAL_13" ;;
"Tatami") xsetroot -name "fsignal:$SIGNAL_14" ;;
"Previous Layout") xsetroot -name "fsignal:$SIGNAL_16" ;;
"Next Layout") xsetroot -name "fsignal:$SIGNAL_18" ;;
esac
