#!/bin/bash
# dynamic window manager status bar
# Written by speedie.gq for https://speedie.gq/dwm
# Licensed under the GNU GPLv3 free software license.

# NOTE: Anything in the DISPLAY function will be printed to your status bar.
# This means the output of a command will be printed as well.
DISPLAY() {
  echo "\
<  $(echo $(free -h --giga | awk '/^Mem/ {print $3}')B) \
<  $(date +%H:%M) \
<  $(date +%d/%m/%Y) \
<  $(echo $(amixer -c 0 get Master | tail -n1 | sed -r "s/.*\[(.*)%\].*/\1/")%) \
<  $(echo $(curl wttr.in/?format=3 | sed 's/.* //' | sed 's/.*\(.....\)/\1/')) \
<  $(awk '{$1=$1/1024000; print $1"B";}' /sys/class/net/[ew]*/statistics/tx_bytes | sed 's/.*\(....\)/\1/')" \

# Check if we're recording with dfmpeg or not
if [ -e "/tmp/dfmpeg-recording" ]; then
		echo " <  Recording"
fi

# CPU temp
if [ -e "/usr/bin/sensors" ]; then
		echo " <  $(sensors | grep "temp1" | sed 's/(.*//' | sed "s/temp1.//" | sed -r 's/\s+//g')"
fi

# Music
if [ "$(echo $(mocp -Q %file))" = "" ]; then
		a=$a
else
		echo " <  $(mocp -Q %file | awk -F/ '$0=$NF' | sed "s|[.]...||")"
fi

# RSS
if [ -e "/usr/bin/newsboat" ]; then
		if [[ "$(newsboat -x print-unread)" =~ "Error" ]]; then
				cat /tmp/newsboat
		else
				echo " <  $(newsboat -x print-unread | sed "s| unread articles||") unread!" > /tmp/newsboat && cat /tmp/newsboat
		fi
fi

}

BASE() {
  SLEEPTIME=5
}

PRINT() {
  xsetroot -name "$(DISPLAY)"
}

BASE

PRINT && sleep $SLEEPTIME && $0 && exit 0
