/*
* Xresources preferences to load at startup
* You can add more if you know what you're doing.
*/
ResourcePref resources[]                      = {
       { "font",                 STRING,  &font },
       { "font2",                STRING,  &font2 },
	   { "font3",                STRING,  &font3 },
	   { "col_background",       STRING,  &col_background },
       { "col_backgroundmid",    STRING,  &col_backgroundmid },
       { "col_textnorm",         STRING,  &col_textnorm },
       { "col_windowbordersel",  STRING,  &col_windowbordersel },
       { "col_windowbordernorm", STRING,  &col_windowbordernorm },
	   { "col_textsel",          STRING,  &col_textsel },
	   { "col_tag1",             STRING,  &col_tag1 },
	   { "col_tag1_text",        STRING,  &col_tag1_text },
	   { "col_tag2",             STRING,  &col_tag2 },
	   { "col_tag2_text",        STRING,  &col_tag2_text },
	   { "col_tag3",             STRING,  &col_tag3 },
	   { "col_tag3_text",        STRING,  &col_tag3_text },
	   { "col_tag4",             STRING,  &col_tag4 },
	   { "col_tag4_text",        STRING,  &col_tag4_text },
	   { "col_tag5",             STRING,  &col_tag5 },
	   { "col_tag5_text",        STRING,  &col_tag5_text },
	   { "col_tag6",             STRING,  &col_tag6 },
	   { "col_tag6_text",        STRING,  &col_tag6_text },
	   { "col_tag7",             STRING,  &col_tag7 },
	   { "col_tag7_text",        STRING,  &col_tag7_text },
	   { "col_tag8",             STRING,  &col_tag8 },
	   { "col_tag8_text",        STRING,  &col_tag8_text },
	   { "col_tag9",             STRING,  &col_tag9 },
	   { "col_tag9_text",        STRING,  &col_tag9_text },

       /* pywal support */
	   { "color0",               STRING,  &col_background },
	   { "color4",               STRING,  &col_backgroundmid },
	   { "color4",               STRING,  &col_textnorm },
	   { "color8",               STRING,  &col_windowbordersel },
	   { "color0",               STRING,  &col_windowbordernorm },
	   { "color0",               STRING,  &col_textsel },
	   { "color1",               STRING,  &col_tag1 },
	   { "color0",               STRING,  &col_tag1_text },
       { "color2",               STRING,  &col_tag2 },
	   { "color0",               STRING,  &col_tag2_text },
	   { "color3",               STRING,  &col_tag3 },
	   { "color0",               STRING,  &col_tag3_text },
	   { "color4",               STRING,  &col_tag4 },
	   { "color0",               STRING,  &col_tag4_text },
	   { "color5",               STRING,  &col_tag5 },
       { "color0",               STRING,  &col_tag5_text },
	   { "color6",               STRING,  &col_tag6 },
       { "color0",               STRING,  &col_tag6_text },
       { "color7",               STRING,  &col_tag7 },
	   { "color0",               STRING,  &col_tag7_text },
	   { "color8",               STRING,  &col_tag8 },
	   { "color0",               STRING,  &col_tag8_text },
	   { "color9",               STRING,  &col_tag9 },
	   { "color0",               STRING,  &col_tag9_text },

	   { "shell",                STRING,  &shell },
       { "status",               STRING,  &status },
       { "lockfullscreen",       INTEGER, &lockfullscreen },
	   { "borderpx",             INTEGER, &borderpx }, 
       { "snap",                 INTEGER, &snap },
       { "showbar",              INTEGER, &showbar },
       { "topbar",               INTEGER, &topbar },
       { "nmaster",              INTEGER, &nmaster },
       { "resizehints",          INTEGER, &resizehints },
       { "startontag",           INTEGER, &startontag },
	   { "gappx",                INTEGER, &gappx },
       { "sizeicon",             INTEGER, &sizeicon },
	   { "decorhints",           INTEGER, &decorhints },
       { "swallowfloating",      INTEGER, &swallowfloating },
	   { "vertpad",              INTEGER, &vertpad },
	   { "sidepad",              INTEGER, &sidepad },
	   { "mfact",                FLOAT,   &mfact },
/*       value in .Xresources    type     value in dwm */
};
