#!/bin/sh
# This script is from the suckless.org website.
# I made the following changes to it:
# - POSIX compliant
# - Tab goes down, j/k to navigate
# - Removed class from $windows making it look nicer
# - Other small improvements.

RESTORE() {
  xmodmap -e "keycode 23 = Tab"
  xmodmap -e "keycode 116 = Down"

  # Vim
  xmodmap -e "keycode 44 = j"
  xmodmap -e "keycode 45 = k"
}

case "$RUNLAUNCHER" in
"") RUNLAUNCHER=dmenu ;;
esac

wmctrl -xl || exit 1

SET() {
  xmodmap -e "keycode 23 = Down"
  xmodmap -e "keycode 116 = Tab"

  # Vim
  xmodmap -e "keycode 44 = Down"
  xmodmap -e "keycode 45 = Up"
}

SET

windows=$(wmctrl -xl | tr -s '[:blank:]' | cut -d ' ' -f 3-3,5- | sed 's/^[a-zA-Z0-9-]*\.//' | sort | uniq)
windows_class=$(echo $windows | awk '{ print $1 }')

# If only one window is open, don't display the menu.
case "$(printf "$windows" | wc -l)" in
"1") RESTORE && exit 1 ;;
esac

# Add spaces to align the WM_NAMEs of the windows
max=$(echo "$windows" | awk '{cur=length($1); max=(cur>max?cur:max)} END{print max}')

windows=$(echo "$windows" | \
              awk -v max="$max" \
                  '{cur=length($1); printf $1; \
                    for(i=0; i < max - cur + 1; i++) printf " "; \
                    $1 = ""; printf "%s\n", $0}')


target=$(printf "\n$windows" | cut -f 2- -d ' ' | sed 's/^ *//g' | $RUNLAUNCHER -b -l 10 -g 1 -p "Which window?" | tr -s '[:blank:]' | cut -d ' ' -f 2-)

case "$target" in
"") RESTORE && exit 0 ;;
esac

wmctrl -a "$target"

RESTORE
