#!/bin/sh
# audioctrl

MUTE() {
  # Mute for pulseaudio/pipewire
  if [ "$AUDIO" = "pulse" ]; then
		if [ -e "/usr/bin/pulsemixer" ]; then
				pulsemixer --toggle-mute
				if [ -e "/usr/bin/notify-send" ]; then
						notify-send "Toggled mute."
				fi
		fi
  else
        # Mute for alsa
		amixer sset Master toggle
				if [ -e "/usr/bin/notify-send" ]; then
						notify-send "Toggled mute."
				fi
  fi
}

RAISE() {
  if [ "$AUDIO" = "pulse" ]; then
		if [ -e "/usr/bin/pulsemixer" ]; then
				pulsemixer --change-volume +7
			    if [ -e "/usr/bin/notify-send" ]; then
						notify-send "Increased volume by 7%.($(amixer -c 0 get Master | tail -n 1 | sed -r "s/.*\[(.*)%\].*/\1/")%)"
				fi
		fi
  else
		amixer -c 0 set Master 7%+
		if [ -e "/usr/bin/notify-send" ]; then
				notify-send "Increased volume by 7%. ($(amixer -c 0 get Master | tail -n 1 | sed -r "s/.*\[(.*)%\].*/\1/")%)"
		fi
  fi
}

LOWER() {
  if [ "$AUDIO" = "pulse" ]; then
		if [ -e "/usr/bin/pulsemixer" ]; then
				pulsemixer --change-volume -7
		        if [ -e "/usr/bin/notify-send" ]; then
						notify-send "Decreased volume by 7%. ($(amixer -c 0 get Master | tail -n 1 | sed -r "s/.*\[(.*)%\].*/\1/")%)"
				fi
		fi
  else
		amixer -c 0 set Master 7%-
		if [ -e "/usr/bin/notify-send" ]; then
				notify-send "Decreased volume by 7%. ($(amixer -c 0 get Master | tail -n 1 | sed -r "s/.*\[(.*)%\].*/\1/")%)"
		fi
  fi
}

SWITCH() {
  ls $HOME/.local/share/audioctrl-status || echo "0" > $HOME/.local/share/audioctrl-status
  if [ "$(cat $HOME/.local/share/audioctrl-status)" = "0" ]; then
		amixer -c 0 sset 'Auto-Mute Mode' Enabled ; echo "1" > $HOME/.local/share/audioctrl-status
		if [ -e "/usr/bin/notify-send" ]; then
				notify-send "Switched to headphones."
		fi
  else
		amixer -c 0 sset 'Auto-Mute Mode' Disabled ; echo "0" > $HOME/.local/share/audioctrl-status
		if [ -e "/usr/bin/notify-send" ]; then
				notify-send "Switched to speakers."
		fi
  fi
}

AUDIO=alsa

if [ -e "$HOME/.local/share/audioctrl-sound" ]; then
		if [ "$(cat $HOME/.local/share/audioctrl-sound)" = "" ]; then
				AUDIO=alsa
		else
				AUDIO=pulseaudio
		fi
else
		pgrep -x pulseaudio > $HOME/.local/share/audioctrl-pulseaudio
		pgrep -x pipewire > $HOME/.local/share/audioctrl-pipewire
		cat $HOME/.local/share/audioctrl-pipewire $HOME/.local/share/audioctrl-pulseaudio > $HOME/.local/share/audioctrl-sound
fi

printf "\nAudio = $AUDIO\n"

case "$1" in
"-mute") MUTE ;;
"-raise") RAISE ;;
"-lower") LOWER ;;
"-switch") SWITCH ;;
esac

# Update status
pkill status && status &
