#!/bin/sh
# dwm-core
# This script handles the systray and other things necessary for usage.

BINDIR=$(cat /usr/share/dwm-bindir) # Set binary directory to the contents of this variable.

TINT="222222" # Default tint
EDGE="top" # Part of the screen where your systray will be placed
GET_EDGE_AUTO="true" # Get edge automatically (true/false)
SYSTRAY_COL=1 # When using pywal, set color to background (1) or backgroundmid (0)
EXPORTDIR=$HOME/.config/dwm-de/systray # Config directory
mkdir -p $EXPORTDIR

# Load config if available and override settings
if [ -e "$EXPORTDIR/config" ]; then
		. $EXPORTDIR/config
else
		printf "TINT=$TINT # Tint when pywal is not used." > $EXPORTDIR/config
		printf "\nEDGE=$EDGE # Part of the screen where your systray will be placed" >> $EXPORTDIR/config
		printf "\nGET_EDGE_AUTO=$GET_EDGE_AUTO # Get edge automatically (true/false)" >> $EXPORTDIR/config
		printf "\nSYSTRAY_COL=$SYSTRAY_COL # When using pywal, set color to background (1) or backgroundmid (0)" >> $EXPORTDIR/config
fi

TINT="$(echo $TINT | sed "s|#||g")"
OPT=$1

# Pywal tint
PYWAL_TINT() {
  # Pywal tint
  if [ -e "$HOME/.cache/wal/colors" ]; then
		if [ "$SYSTRAY_COL" = "1" ]; then
				TINT=$(sed -n 1,1p $HOME/.cache/wal/colors | sed "s|#||g")
		else
				TINT=$(sed -n 13,13p $HOME/.cache/wal/colors | sed "s|#||g")
		fi
  fi
}

# Set edge
SETEDGE() {
		if [ "$GET_EDGE_AUTO" = "true" ]; then
				if [ -e "/usr/share/dwm-topbar" ]; then
						EDGE="top"
				else
						EDGE="bottom"
				fi
		fi
}

PYWAL_TINT
SETEDGE

USE() {
  # Toggle
  TOGGLE() {
    if [ -e "/tmp/systray-started" ]; then
		  OPT="-stop"
    else
		  OPT="-start"
    fi
		  
  }
  
  case "$OPT" in
  "-toggle") TOGGLE ;;
  esac
  
  case "$OPT" in
  "-start") trayer --edge $EDGE --align right --SetDockType true --SetPartialStrut true --expand true --width 8 --transparent true --alpha 0 --tint 0x${TINT} --height 10 &
		    touch /tmp/systray-started ; pkill status ; status & ;;
  "-stop") rm -f /tmp/systray-started ; pkill trayer ; pkill status ; status & ;;
  "") echo "-start | Start the systray and restart status\n-stop | Stop the systray and restart status\n-toggle | Toggle systray and restart status" ;;
  esac
}

case "$OPT" in
"-curl-weather") clear ; curl -s wttr.in | head -n 38 | tail -n 37 && sleep 60 ;;
"-curl-cheatsheet") clear ; echo -n "What cheatsheet do you want to view?\nExample: vim\n > " ; read CHEATSHEET ; curl -s cheat.sh/$(echo $CHEATSHEET | tr '[:upper:]' '[:lower:]') > /tmp/cheatsheet
grep "Unknown topic." /tmp/cheatsheet && $0 -curl-cheatsheet && exit 0 
less /tmp/cheatsheet ;;
esac

# Start systray
if [ -e "${BINDIR}trayer" ]; then
		USE
else
		echo "Trayer not installed, exiting." && exit 1
fi
