#!/bin/sh
COL2="$(printf '\033[0;35m')" # Color 2
COL1="$(printf '\033[0m')" # Color 1
O=$1

echo "${0}. Run '$0 -h' to see a list of arguments or to jump to a specific section.\n$(cat /usr/share/dwm-about /usr/share/dwm-patchlist /usr/share/dwm-about-2 /usr/share/dwm-bindlist /usr/share/dwm-deplist /usr/share/dwm-about-3 /usr/share/dwm-xresources /usr/share/dwm-about-4 /usr/share/dwm-fsignal /usr/share/dwm-about-5 | sed 's|xsetroot -name "fsignal:||g' | sed 's|"||g')" > /tmp/dwm-doc

case "$O" in
"-w") cat /tmp/dwm-doc | tail -n $(expr $(cat /tmp/dwm-doc | wc -l) "-" 1) > ../readme ;;
"-wmd") cat /tmp/dwm-doc | \
						 tail -n $(expr $(cat /tmp/dwm-doc | wc -l) "-" 1) | \
				         sed "s|-- speedie's fork of dynamic window manager --|# speedie's fork of dynamic window manager|g" | \
						 sed "s|-- What is dwm? --|## What is dwm?|g" | \
						 sed "s|-- Installation --|## Installation|g" | \
						 sed "s|-- Layouts --|## Layouts|g" | \
						 sed "s|-- Patches --|## Patches|g" | \
						 sed "s|-- Keybinds --|## Keybinds|g" | \
						 sed "s|-- Applications --|### Applications|g" | \
						 sed "s|-- Navigation --|### Nagigation|g" | \
						 sed "s|-- Extras --|### Extras|g" | \
						 sed "s|-- Dependencies --|## Dependencies|g" | \
						 sed "s|-- Features --|## Features|g" | \
						 sed "s|-- Software --|## Software|g" | \
						 sed "s|-- Important --|## Important|g" | \
						 sed "s|-- .Xresources and Pywal --|## .Xresources and Pywal|g" | \
						 sed "s|-- Fsignal --|## Fsignal|g" | \
						 sed "s|-- Switching run launcher --|## Switching run launcher|g" > ../README.md ;;
"-whtml") $0 -wmd
		  markdown ../README.md > ../readme.html || printf "\nmarkdown-to-html not found, install using:\nnpm install markdown-to-html -g\n" && exit 1 ;;
"") printf "Hello, I'm your dwm guide. How can I help you?\nNo arguments to view this list of arguments.\n-h | View this list of arguments.\n-a | View everything.\n-1 | What is dwm?\n-2 | List of patches\n-3 | List of all keybinds\n-4 | List of all dependencies\n-5 | .Xresources/Pywal information.\n-6 | Fsignal information\n-7 | Switching run launcher\n-8 | Installation\n-9 | Layouts\n-10| Important information.\n-w | Write documentation to ../readme\n-wmd | Write documentation (Markdown)\n-whtml | Write documentation (HTML) using markdown-to-html.\n"; exit 0 ;;
"-h") printf "Hello, I'm your dwm guide. How can I help you?\nNo arguments to view this list of arguments.\n-h | View this list of arguments.\n-a | View everything.\n-1 | What is dwm?\n-2 | List of patches\n-3 | List of all keybinds\n-4 | List of all dependencies\n-5 | .Xresources/Pywal information.\n-6 | Fsignal information\n-7 | Switching run launcher\n-8 | Installation\n-9 | Layouts\n-10| Important information.\n-w | Write documentation to ../readme\n-wmd | Write documentation (Markdown)\n-whtml | Write documentation (HTML) using markdown-to-html.\n"; exit 0 ;;
"-1") cat /usr/share/dwm-about | sed "s|--|${COL2}--${COL1}|g" | head -n 10 | less ;;
"-2") cat /usr/share/dwm-about /usr/share/dwm-patchlist | sed "s|--|${COL2}--${COL1}|g" | tail -n 60 | less ;;
"-3") cat /usr/share/dwm-about-2 /usr/share/dwm-bindlist | sed "s|--|${COL2}--${COL1}|g" | less ;;
"-4") cat /usr/share/dwm-deplist | sed "s|--|${COL2}--${COL1}|g" | less ;;
"-5") cat /usr/share/dwm-about-3 /usr/share/dwm-xresources | tail -n 59 | sed "s|--|${COL2}--${COL1}|g" | less ;;
"-6") cat /usr/share/dwm-about-4 /usr/share/dwm-fsignal | sed "s|--|${COL2}--${COL1}|g" | sed 's|xsetroot -name "fsignal:||g' | sed 's|"||g' | less ;;
"-7") cat /usr/share/dwm-about-5 | sed "s|--|${COL2}--${COL1}|g" | less ;;
"-8") cat /usr/share/dwm-about | sed "s|--|${COL2}--${COL1}|g" | head -n 22 | tail -n 11 | less ;;
"-9") cat /usr/share/dwm-about | sed "s|--|${COL2}--${COL1}|g" | tail -n 22 | head -n 19 | less ;;
"-10") cat /usr/share/dwm-about-3 | sed "s|--|${COL2}--${COL1}|g" | head -n 24 | less ;;
"-a") cat /tmp/dwm-doc | sed "s|--|${COL2}--${COL1}|g" | less ;;
esac
