#!/bin/sh
# External script which starts dwm!
# https://speedie.gq/dwm for instructions!

XRESOURCES() {
test $HOME/.Xresources && xrdb $HOME/.Xresources
test $HOME/.config/.Xresources && xrdb $HOME/.config/.Xresources
}

RESET() {
$HOME/.config/swal/swal_wm
xsetroot -name "fsignal:25"
xsetroot -name "Loading" # To hide the ugly fsignal status
xsetroot -name "fsignal:30"
xsetroot -name "Loading" # To hide the ugly fsignal status
}

START_DWM() {
pgrep -x dwm && exit 0
while true; do
dwm > /tmp/dwm-log
done
}

case "$1" in
"") XRESOURCES ; RESET ; START_DWM ; exit 0 ;;
"-r") RESET ; exit 0 ;;
esac

exit 0
