#!/bin/sh

cd $1

case "$RUNLAUNCHER" in
"") RUNLAUNCHER=dmenu ;;
esac

SELPDF=$(ls -Ap1 *.pdf | $RUNLAUNCHER -g 1 -l 50 -p "What PDF do you want to open?")

case "$SELPDF" in
"") exit 0 ;;
esac

$2 "$1/$SELPDF"
