#!/bin/sh
# This script is from the suckless.org website.
# I'm not sure who made it initially but I made it POSIX compliant.
# I also added some xmodmap stuff so that it's nicer to use.

case "$RUNLAUNCHER" in
"") RUNLAUNCHER=dmenu ;;
esac

wmctrl -xl || exit 1
xmodmap -e "keycode 23 = Down"
xmodmap -e "keycode 116 = Tab"

# Vim
xmodmap -e "keycode 44 = Down"
xmodmap -e "keycode 45 = Up"

windows=$(wmctrl -xl | tr -s '[:blank:]' | cut -d ' ' -f 3-3,5- | sed 's/^[a-zA-Z0-9-]*\.//' | sort | uniq)

# Add spaces to align the WM_NAMEs of the windows
max=$(echo "$windows" | awk '{cur=length($1); max=(cur>max?cur:max)} END{print max}')

windows=$(echo "$windows" | \
              awk -v max="$max" \
                  '{cur=length($1); printf $1; \
                    for(i=0; i < max - cur + 1; i++) printf " "; \
                    $1 = ""; printf "%s\n", $0}')


target=$(echo "$windows" | $RUNLAUNCHER -b -l 10 -g 1 -p "Which window?" | tr -s '[:blank:]' | cut -d ' ' -f 2-)
wmctrl -a "$target"

xmodmap -e "keycode 23 = Tab"
xmodmap -e "keycode 116 = Down"

# Vim
xmodmap -e "keycode 44 = j"
xmodmap -e "keycode 45 = k"
